
name: AWS Osaka Pro
on:
  schedule:
    - cron: '0 */3 * * *' # 每3小时执行一次
  workflow_dispatch:

env:
  INSTANCE_ID: i-01636fd58d539173b
  REGION: ap-northeast-3
  DOMAIN: 'osaka.onemorething.pp.ua' # 需要查询的DNS名称
  CF_ZONE_ID: 1fa9774064820f53fe1733e37a19f721
  CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }} # 从GitHub Secrets中获取API Token
  PROXIED: 'false' # 是否开启Cloudflare代理，默认否
  MAX_RETRIES: 5

jobs:
  healthcheck_and_manage_ec2:
    runs-on: ubuntu-latest
    steps:
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_Osaka }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_Osaka }}
        aws-region: ${{ env.REGION }}

    - name: Get Current Public IP
      id: get_current_ip
      run: |
        CURRENT_IP=$(aws ec2 describe-instances --instance-ids ${{ env.INSTANCE_ID }} --region ${{ env.REGION }} --query 'Reservations[0].Instances[0].PublicIpAddress' --output text)
        echo "Current Public IP: $CURRENT_IP"
        echo "CURRENT_IP=$CURRENT_IP" >> $GITHUB_ENV

    - name: Check Current IP Connectivity
      id: ping_check
      run: |
        API_URL="https://v2.api-m.com/api/tcping?address=${{ env.CURRENT_IP }}&port=1081"
        response=$(curl -sL $API_URL)
        echo ${{ env.CURRENT_IP }} $response
        if [[ $response == *"200"* ]]; then
          echo "Current IP is pingable at $(date)"
          echo "::set-output name=pingable::true"
        else
          echo "Current IP is NOT pingable at $(date)"
          echo "::set-output name=pingable::false"
        fi

    - name: Allocate and Associate Elastic IP
      if: steps.ping_check.outputs.pingable == 'false'
      id: allocate_and_associate_ip
      run: |
        for (( i=1; i<=${{ env.MAX_RETRIES }}; i++ )); do
          echo "Attempt $i to allocate a new Elastic IP."
          NEW_ALLOCATED_IP=$(aws ec2 allocate-address --region ${{ env.REGION }} --query 'PublicIp' --output text)
          echo "Allocated New Elastic IP: $NEW_ALLOCATED_IP"

          echo "Associating Elastic IP with the instance..."
          aws ec2 associate-address --instance-id ${{ env.INSTANCE_ID }} --public-ip $NEW_ALLOCATED_IP --region ${{ env.REGION }}

          # Check if the new IP is reachable
          API_URL="https://v2.api-m.com/api/tcping?address=${{ env.NEW_ALLOCATED_IP }}&port=1081"
          response=$(curl -sL $API_URL)
          echo ${{ env.NEW_ALLOCATED_IP }} $response

          if [[ $response == *"200"* ]]; then
            echo "New Elastic IP is pingable at $(date)"
            echo "NEW_ALLOCATED_IP=$NEW_ALLOCATED_IP" >> $GITHUB_ENV
            echo "::set-output name=pingable::true"
            break
          else
            echo "New Elastic IP is NOT pingable at attempt $i."
            # Optional: Release the allocated IP if it's not usable
            aws ec2 release-address --public-ip $NEW_ALLOCATED_IP --region ${{ env.REGION }}
          fi

          sleep 5 # 向API发送请求之间等待以避免速率限制
        done

        if [[ $response != *"200"* ]]; then
          echo "All attempts failed. No valid Elastic IP found."
          exit 1
        fi

    - name: Get Cloudflare DNS Record ID
      if: steps.allocate_and_associate_ip.outputs.pingable == 'true'
      run: |
        # 使用cURL调用Cloudflare API获取DNS记录ID
        DNS_RECORDS=$(curl -s -X GET "https://api.cloudflare.com/client/v4/zones/${{ env.CF_ZONE_ID }}/dns_records?name=${{ env.DOMAIN }}" \
          -H "Authorization: Bearer ${{ env.CF_API_TOKEN }}" \
          -H "Content-Type: application/json")
        DNS_ID=$(echo "${DNS_RECORDS}" | jq -r '.result[] | select(.name == "'${{ env.DOMAIN }}'") | .id')
        if [ -z "$DNS_ID" ]; then
          echo "No DNS record found for ${{ env.DOMAIN }}"
          exit 1
        else
          echo "DNS Record ID for ${{ env.DOMAIN }}: $DNS_ID"
          echo "DNS_ID=$DNS_ID" >> $GITHUB_ENV
        fi

    - name: Update DNS Record
      if: steps.allocate_and_associate_ip.outputs.pingable == 'true'
      run: |
        NEW_IP=${{ env.NEW_ALLOCATED_IP }}
        echo "Updating DNS record with new Elastic IP..."
        # 更新 DNS 记录的原有代码
        UPDATE_CMD=$(echo -n "{\"type\":\"A\",\"name\":\"${{ env.DOMAIN }}\",\"content\":\"$NEW_IP\",\"proxied\":${{ env.PROXIED }}}")
        curl -X PUT "https://api.cloudflare.com/client/v4/zones/${{ env.CF_ZONE_ID }}/dns_records/${{ env.DNS_ID }}" \
          -H "Authorization: Bearer ${{ env.CF_API_TOKEN }}" \
          -H "Content-Type: application/json" \
          --data-raw "$UPDATE_CMD"

        RESPONSE=$(curl -s -o /dev/null -w "%{http_code}" "https://api.cloudflare.com/client/v4/zones/${{ env.CF_ZONE_ID }}/dns_records/${{ env.DNS_ID }}" \
          -H "Authorization: Bearer ${{ env.CF_API_TOKEN }}" \
          -H "Content-Type: application/json")

        if [ "$RESPONSE" -eq 200 ]; then
          echo "DNS record updated successfully."
        else
          echo "Failed to update DNS record. Response code: $RESPONSE"
          exit 1
        fi

    - name: Release All Elastic IPs
      run: |
        ALLOCATED_IPS=$(aws ec2 describe-addresses --query 'Addresses[?AssociationId!=`null`].AllocationId' --output text)
        if [ -n "$ALLOCATED_IPS" ]; then
          for ALLOCATION_ID in $ALLOCATED_IPS; do
            aws ec2 release-address --allocation-id $ALLOCATION_ID --region ${{ env.REGION }}
            echo "Released Elastic IP with Allocation ID: $ALLOCATION_ID"
          done
        else
          echo "No Elastic IPs to release."
        fi
