name: CF DNS UPDATE TEST
on:
  workflow_dispatch:
  
jobs:
  update_cloudflare-dns:
    runs-on: ubuntu-latest
    steps:
    - name: Update Cloudflare DNS
      env:
        CF_ZONE_ID: ${{ env.CF_ZONE_ID }}
        CF_API_KEY: ${{ secrets.CF_API_KEY }} # 使用从Secrets加载的API密钥
        DOMAIN: ca.nets.pp.ua
        Email: will_pan@me.com
        Key: 15c49068b805a7a078b81b1a3dd9690d8c31d
        NEW_IP: 1.1.1.1
      run: |
        echo "Updating Cloudflare DNS record for $DOMAIN to IP: $NEW_IP"
          curl -X PUT "https://api.cloudflare.com/client/v4/zones/$CF_ZONE_ID/dns_records?name=$DOMAIN&type=A" \
            -H "X-Auth-Email: $Email" \
            -H "X-Auth-Key: $Key" \
            -H "Content-Type: application/json" \
            --data "{\"type\":\"A\",\"name\":\"$DOMAIN\",\"content\":\"$NEW_IP\",\"ttl\":120}"
