name: Get Cloudflare DNS Record ID

on:
  workflow_dispatch:

jobs:
  get_dns_record_id:
    runs-on: ubuntu-latest
    steps:
    - name: Get Cloudflare DNS Record ID
      env:
        CF_ZONE_ID: b2fc014bf87f67714afb1b9c10941a2e # 从Secrets获取Zone ID
        CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }} # 从Secrets获取API Token
        DNS_NAME: 'ca.nets.pp.ua' # 需要查询的DNS名称
      run: |
        # 使用cURL调用Cloudflare API获取DNS记录ID
        RECORD_ID=$(curl -s -X GET "https://api.cloudflare.com/client/v4/zones/${{ env.CF_ZONE_ID }}/dns_records?name=${{ env.DNS_NAME }}" \
          -H "Authorization: Bearer ${{ env.CF_API_TOKEN }}" \
          -H "Content-Type: application/json")

        # 解析响应并提取记录ID
        RECORD_ID=$(echo "${RECORD_ID}" | jq -r '.result[] | select(.name == "'${{ env.DNS_NAME }}'") | .id')

        if [ -z "$RECORD_ID" ]; then
          echo "No DNS record found for ${{ env.DNS_NAME }}"
          exit 1
        else
          echo "Record ID for ${{ env.DNS_NAME }}: $RECORD_ID"
        fi
