name: IP Management Pro

on:
  #schedule:
  #  - cron: '0 */3 * * *' # 每3小时运行一次
  workflow_dispatch:

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install PyYAML
      run: pip install pyyaml

    - name: Parse YAML and set environment variables
      run: |
        python parse_yaml.py
        cat env_vars.txt >> $GITHUB_ENV

    - name: Print Environment Variables
      run: |
        echo "DOMAIN_0: $DOMAIN_0"
        echo "GCP_VM_NAME_0: $GCP_VM_NAME_0"
        echo "GCP_VM_ZONE_0: $GCP_VM_ZONE_0"
        echo "GCP_REGION_0: $GCP_REGION_0"
        # Repeat for other servers if needed

  ip_management:
    needs: setup
    runs-on: ubuntu-latest
    strategy:
      matrix:
        server_index: [0, 1, 2]

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Authentication
      uses: google-github-actions/auth@v2
      with:
        credentials_json: '${{ secrets.GCP_SA_KEY }}'

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v2

    - name: Use gcloud CLI
      run: gcloud info

    - name: Check Domain Connectivity
      id: check-connectivity
      run: |
        API_URL="https://api.jaxing.cc/v2/Tcping?host=${{ env[format('DOMAIN_{0}', matrix.server_index)] }}&port=${{ env.PORT }}"
        response=$(curl -sL $API_URL)
        echo "Response for domain ${{ env[format('DOMAIN_{0}', matrix.server_index)] }}: $response"
        if [[ $response == *'"msg":"请求成功"'* ]] && ! echo "$response" | grep -q '"dial tcp'; then
          echo "Domain ${{ env[format('DOMAIN_{0}', matrix.server_index)] }} is reachable."
          echo "REACHABLE=true" >> $GITHUB_ENV
        else
          echo "Domain ${{ env[format('DOMAIN_{0}', matrix.server_index)] }} is unreachable."
          echo "REACHABLE=false" >> $GITHUB_ENV
        fi

    - name: Get Current VM External IP
      if: env.REACHABLE == 'false'
      id: get_current_ip
      run: |
        CURRENT_IP=$(gcloud compute instances describe ${{ env[format('GCP_VM_NAME_{0}', matrix.server_index)] }} --zone=${{ env[format('GCP_VM_ZONE_{0}', matrix.server_index)] }} --format='value(networkInterfaces[0].accessConfigs[0].natIP)')
        echo "Current IP is $CURRENT_IP"
        echo "CURRENT_IP=$CURRENT_IP" >> $GITHUB_ENV

    - name: Reconfig VM and Test IP
      if: env.REACHABLE == 'false'
      id: reconfig_vm_and_test_ip
      run: |
        retry_count=0
        max_retries=5
        vm_name=${{ env[format('GCP_VM_NAME_{0}', matrix.server_index)] }}
        vm_zone=${{ env[format('GCP_VM_ZONE_{0}', matrix.server_index)] }}
        region=${{ env[format('GCP_REGION_{0}', matrix.server_index)] }}
        static_ips=()
        while (( retry_count < max_retries )); do
            CURRENT_IP=$(gcloud compute instances describe $vm_name --zone=$vm_zone --format='value(networkInterfaces[0].accessConfigs[0].natIP)')
            CURRENT_ACCESS_CONFIG_NAME=$(gcloud compute instances describe "$vm_name" --zone="$vm_zone" --format='value(networkInterfaces[0].accessConfigs[0].name)')
            STATIC_IP_NAME="${vm_name}$(printf "%02d" $((retry_count + 1)))"
            gcloud compute addresses create $STATIC_IP_NAME --addresses=$CURRENT_IP --region=$region
            static_ips+=("$STATIC_IP_NAME")
            gcloud compute instances delete-access-config $vm_name --zone=$vm_zone --access-config-name=$CURRENT_ACCESS_CONFIG_NAME
            gcloud compute instances add-access-config $vm_name --zone=$vm_zone
            NEW_IP=$(gcloud compute instances describe $vm_name --zone=$vm_zone --format='value(networkInterfaces[0].accessConfigs[0].natIP)')
            API_URL="https://api.jaxing.cc/v2/Tcping?host=$NEW_IP&port=${{ env.PORT }}"
            response=$(curl -sL "$API_URL")
            if [[ $response == *'"msg":"请求成功"'* ]] && ! echo "$response" | grep -q '"dial tcp'; then
                echo "New IP $NEW_IP is reachable, proceeding with the rest of the process."
                echo "NEW_IP=$NEW_IP" >> $GITHUB_ENV
                break
            else
                echo "New IP $NEW_IP is not reachable, retrying..."
                ((retry_count+=1))
                sleep 5
            fi
        done
        if [ $retry_count -eq $max_retries ]; then
            echo "Reached maximum retries, unable to configure VM."
        else
            echo "VM is now using a reachable IP: $NEW_IP"
        fi
        for STATIC_IP in "${static_ips[@]}"; do
            gcloud compute addresses delete $STATIC_IP --region=$region
        done

    - name: Get Cloudflare DNS Record ID
      if: env.REACHABLE == 'false'
      run: |
        DNS_RECORDS=$(curl -s -X GET "https://api.cloudflare.com/client/v4/zones/${{ env.CF_ZONE_ID }}/dns_records?name=${{ env.DOMAIN }}" \
          -H "Authorization: Bearer ${{ env.CF_API_TOKEN }}" \
          -H "Content-Type: application/json")
        DNS_ID=$(echo "${DNS_RECORDS}" | jq -r '.result[] | select(.name == "${{ env.DOMAIN }}") | .id')
        if [ -z "$DNS_ID" ]; then
          echo "No DNS record found for ${{ env.DOMAIN }}"
          exit 1
        else
          echo "DNS Record ID for ${{ env.DOMAIN }}: $DNS_ID"
          echo "DNS_ID=$DNS_ID" >> $GITHUB_ENV
        fi
    - name: Update DNS Record
      if: env.REACHABLE == 'false'
      run: |
        UPDATE_CMD=$(echo -n "{\"type\":\"A\",\"name\":\"${{ env.DOMAIN }}\",\"content\":\"$NEW_IP\",\"proxied\":${{ env.PROXIED }}}")
        curl -X PUT "https://api.cloudflare.com/client/v4/zones/${{ env.CF_ZONE_ID }}/dns_records/${{ env.DNS_ID }}" \
          -H "Authorization: Bearer ${{ env.CF_API_TOKEN }}" \
          -H "Content-Type: application/json" \
          --data-raw "$UPDATE_CMD"
        RESPONSE=$(curl -s -o /dev/null -w "%{http_code}" "https://api.cloudflare.com/client/v4/zones/${{ env.CF_ZONE_ID }}/dns_records/${{ env.DNS_ID }}" \
          -H "Authorization: Bearer ${{ env.CF_API_TOKEN }}" \
          -H "Content-Type: application/json")
        if [ "$RESPONSE" -eq 200 ]; then
          echo "DNS record updated successfully."
        else
          echo "Failed to update DNS record. Response code: $RESPONSE"
          exit 1
        fi

    - name: Log Summary
      if: always()
      run: |
        if [ "${{ env.REACHABLE }}" == 'true' ]; then
          echo "Summary: Domain was reachable. No action taken."
        elif [ -n "$NEW_IP" ]; then
          echo "Summary: DNS record updated to $NEW_IP after instance reconfiguration."
        else
          echo "Summary: Unexpected error occurred. No DNS update performed."
        fi
