name: IP Management Pro

on:
  schedule:
    - cron: '0 */3 * * *' # 每3小时运行一次
  workflow_dispatch:

env:
  GCP_PROJECT_ID: skillful-cider-440305-d7
  GCP_SA_KEY: ${{ secrets.GCP_SA_KEY_025 }}
  CF_ZONE_ID: 1fa9774064820f53fe1733e37a19f721
  PORT: 1081
  PROXIED: 'false'
  CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}

jobs:
  read_config:
    runs-on: ubuntu-latest
    outputs:
      server_list: ${{ steps.set-server-list.outputs.server_list }}
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Read and Parse Server Config
      id: set-server-list
      run: |
        server_list=$(cat servers.txt | tr '\n' ',' | sed 's/,$//' | sed 's/,/","/g')
        echo "Server list: $server_list"  # 添加日志记录
        if [ -z "$server_list" ]; then
          echo "Error: Server list is empty or invalid."
          exit 1
        fi
        echo "server_list=$server_list" >> $GITHUB_OUTPUT
