name: Ping Check with Bark Notification

on:
  schedule:
    - cron: '0 */7 * * *'  # 每7小时执行一次
  workflow_dispatch:

jobs:
  tcping_and_notify:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: TCPing Check and Notify
      env:
        DOMAINS: 'hk.onemorething.pp.ua,gcp.tw.onemorething.pp.ua,gcp.kr.onemorething.pp.ua,sydney.nets.pp.ua,ca.nets.pp.ua,osaka.onemorething.pp.ua,gcp.tokyo.onemorething.pp.ua,gcp.london.onemorething.pp.ua,gcp.sg.onemorething.pp.ua'
        BARK_URL: 'https://api.day.app/oZaeqGLJzRLSxW7dJqeACn/'
      run: |
        # 将域名列表分割成数组
        IFS=',' read -ra ADDR <<< "$DOMAINS"
        success_domains=()
        failed_domains=()
        for domain in "${ADDR[@]}"; do
          # 对每个域名执行TCPing检查
          API_URL="https://v2.api-m.com/api/tcping?address=${domain}&port=1081"
          response=$(curl -sL $API_URL)
          echo "$domain $response"
          if [[ $response == *"200"* ]]; then
            success_domains+=("$domain")
          else
            failed_domains+=("$domain")
          fi
        done

        # 构建通知消息
        title="域名检查报告 $(date +'%Y-%m-%d %H:%M:%S')"
        content="可达域名:\n${success_domains[*]} \n不可达域名:\n${failed_domains[*]}"

        # 发送Bark通知
        curl -X POST -H 'Content-Type: application/json' -d "{\"title\":\"$title\",\"body\":\"$content\"}" "$BARK_URL"
