name: Ping Domains

on:
  schedule:
    - cron: '0 * * * *' # 每小时执行一次
  workflow_dispatch: # 允许手动触发

jobs:
  ping-domains:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Ping domains
        run: |
          while IFS= read -r line; do
            domain=$(echo "$line" | cut -d':' -f1)
            port=$(echo "$line" | cut -d':' -f2)
            response=$(curl -s -o /dev/null -w "%{http_code}" "https://v2.api-m.com/api/tcping?address=$domain&port=$port")
            if [ "$response" == "200" ]; then
              echo "Domain $domain on port $port is reachable."
            else
              echo "Domain $domain on port $port is not reachable. Status code: $response"
            fi
          done < domains.txt
        shell: /usr/bin/bash -e {0}
