name: GCP VM IP Management

on:
  workflow_dispatch:

env:
  instance_name: instance-hk
  zone: asia-east2-a
  GCP_PROJECT_ID: infra-falcon-424407-c7
  GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}

jobs:
  ip_management:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - id: 'auth'
      uses: 'google-github-actions/auth@v2'
      with:
        credentials_json: '${{ secrets.GCP_SA_KEY }}'

    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v2'

    - name: 'Use gcloud CLI'
      run: 'gcloud info'

    - name: Setup Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v2.1.0
      with:
        project_id: ${{ env.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true

    - name: Get Current VM External IP
      id: get_current_ip
      run: |
        CURRENT_IP=$(gcloud compute instances describe "${{ env.instance_name }}" --zone="${{ env.zone }}" --format='value(networkInterfaces[0].accessConfigs[0].natIP)')
        echo "::set-output name=current_ip::$CURRENT_IP"
        echo $CURRENT_IP
    - name: reconfig vm and test ip
      id: reconfig_vm_and_test_ip
      run: |
        gcloud compute instances delete-access-config ${{ env.instance_name }} --access-config-name="External NAT" --zone=${{ env.zone }}
        while true; do
            STATUS=$(gcloud compute instances describe "${{ env.instance_name }}" --zone="${{ env.zone }}" --project="${{ env.GCP_PROJECT_ID }}" --format='value(status)')
            if [ "$STATUS" = "RUNNING" ]; then
                echo "instance is running..."
                break
            fi
            echo "Waiting for instance to be running..."
            sleep 10
        done
        gcloud compute instances add-access-config ${{ env.instance_name }} --zone=${{ env.zone }} --project=${{ env.GCP_PROJECT_ID }}
