name: QA GCP VM IP Management

on:
  workflow_dispatch:

env:
  instance_name: instance-hk
  zone: asia-east2-a
  GCP_PROJECT_ID: infra-falcon-424407-c7
  GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}

jobs:
  ip_management:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Setup GCP CLI with Service Account Key
      uses: google-github-actions/setup-gcloud@v2.1.0
      with:
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        project_id: ${{ env.GCP_PROJECT_ID }}

    - name: Get Current VM External IP
      id: get_current_ip
      run: |
        CURRENT_IP=$(gcloud compute instances describe "${{ env.instance_name }}" --zone="${{ env.zone }}" --format='value(networkInterfaces[0].accessConfigs[0].natIP)')
        echo "::set-output name=current_ip::$CURRENT_IP"

    - name: Remove Static IP from VM
      if: steps.get_current_ip.outputs.current_ip != ''
      run: |
        gcloud compute instances remove-access-config "${{ env.instance_name }}" --access-config-name ExternalNAT --zone="${{ env.zone }}"
      
    - name: Allocate New Static IP
      id: allocate_new_ip
      run: |
        # Extracting the region from the zone for address creation
        REGION=$(echo "${{ env.zone }}" | cut -d'-' -f1,2)
        NEW_IP=$(gcloud compute addresses create new-static-ip --region "$REGION" --format='value(address)')
        echo "::set-output name=new_ip::$NEW_IP"
        
    - name: Attach New Static IP to VM
      run: |
        gcloud compute instances add-access-config "${{ env.instance_name }}" --access-config-name ExternalNAT --nat-ip "${{ steps.allocate_new_ip.outputs.new_ip }}" --zone="${{ env.zone }}"
        
    - name: Release Old Static IP (optional)
      if: steps.get_current_ip.outputs.current_ip != ''
      run: |
        # Extracting the region from the zone for address deletion
        REGION=$(echo "${{ env.zone }}" | cut -d'-' -f1,2)
        gcloud compute addresses delete "${{ steps.get_current_ip.outputs.current_ip }}" --region "$REGION" --quiet
