name: TCPing Check

on:
  schedule:
    - cron: '0 * * * *'  # 每小时执行一次，根据需要调整
  workflow_dispatch:

jobs:
  tcping:
    runs-on: ubuntu-latest
    steps:
    - name: TCPing Check
      env:
        DOMAINS: 'hk.nets.pp.ua,tw.nets.pp.ua,kr.nets.pp.ua,melbourne.nets.pp.ua,sydney.nets.pp.ua,ca.nets.pp.ua,osaka.onemorething.pp.ua,tokyo.onemorething.pp.ua,oregon.onemorething.pp.ua'
      run: |
        # 将域名列表分割成数组
        IFS=',' read -ra ADDR <<< "$DOMAINS"
        for domain in "${ADDR[@]}"; do
          # 对每个域名执行TCPing检查
          API_URL="https://v2.api-m.com/api/tcping?address=${domain}&port=1081"
          response=$(curl -s -o /dev/null -w "%{http_code}" "$API_URL")
          if [[ $response == *"200"* ]]; then
            echo "$domain is pingable at $(date)"
          else
            echo "$domain is NOT pingable at $(date)"
          fi
        done
